#!/bin/sh -e

# Copyright (c) 2016-2019 Dmitry Mikhirev
# This software is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See the COPYING file for more details.


die() {
    echo "error: $*" >&2
    exit 1
}

[ $# -eq 1 ] || die "usage: $0 <file>"
[ -f "$1" ] || die "\`$1' does not exist or is not a regular file"

MAGIC=$(dd if="$1" bs=4 count=1 2>/dev/null)
[ "$MAGIC" = Cr24 ] || die "\`$1' is not a chrome extension"

VERSION=$(od -An -j4 -N4 -tu "$1" | tr -d ' \t')
case $VERSION in
    2)
        KEY_LEN=$(od -An -j8 -N4 -tu "$1" | tr -d ' \t')
        SIG_LEN=$(od -An -j12 -N4 -tu "$1" | tr -d ' \t')
        OFFSET=$((16 + KEY_LEN + SIG_LEN))
        ;;
    3)
        HEADER_LEN=$(od -An -j8 -N4 -tu "$1" | tr -d ' \t')
        OFFSET=$((12 + HEADER_LEN))
        ;;
    *)
        die "don't know how to deal with extensions version $VERSION"
        ;;
esac

ZIPMAGIC=$(od -An -j$OFFSET -N4 -tx "$1" | tr -d ' \t')
[ $ZIPMAGIC = 04034b50 ] || die 'payload is not a ZIP archive'

ZIPNAME=$(basename -s .crx "$1").zip

dd if="$1" of="$ZIPNAME" ibs=1 skip=$OFFSET 2>/dev/null
echo "written \`$ZIPNAME'"
